name: build

on:
  push:
    branches: [ main ]
    paths: [ '**.java', '.github/workflows/jacoco.yml', 'pom.xml' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  jacoco-java-maven:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Maven
        run: mvn -B package

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          colors: green yellow orange red
          intervals: 90 75 60

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Commit the badge (if it changed)
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'ivosahlik'
            git config --global user.email 'ivosahlik@seznam.cz'
            git add -A
            git commit -m "Autogenerated JaCoCo coverage badge"
            git push
          fi

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/
